### ISSUE TITLE
[docs/setup]创建

### ISSUE THREAD

**Issue by LoeiFy** [acyortjs/site#26]
当安装好 AcyOrt，可以使用下面命令初始化一个网站 

```bash
$ acyort init <folder>

# 或者
$ cd  <folder>
$ acyort init
```

初始化完成，网站文件夹为以下结构

```
.
├─ config.yml
├─ templates/
|   └─ ccc45/
├─ scripts/
```

**config.yml**

网站配置文件，查看 [配置](/docs/configuration/) 获取更多说明

**templates**

模板文件夹，网站所需要的 [模板](/docs/template/)

**scripts**

自定义脚本目录，用于存放 [插件](/docs/plugin/)

**Comment by Mircc** [comment]
创建的时候提示这个：
RangeError: Maximum call stack size exceeded
    at normalizeStringWin32 (path.js:33:30)
    at Object.resolve (path.js:328:20)

**Comment by LoeiFy** [comment]
@Mircc 是不是有 window defender
